window.TA = window.TA || {};

TA.DATA = {
  seasons: [
    { id: "tide", name: "潮汐季", days: 50, food: 1.1, water: 1.25, wood: 1, energy: 1, desc: "河水上涨，汲取更容易。" },
    { id: "bloom", name: "丰叶季", days: 50, food: 1.35, water: 1, wood: 1.2, energy: 1, desc: "对岸的林莽疯长，浆果坠枝。" },
    { id: "dry", name: "干裂季", days: 50, food: 0.85, water: 0.65, wood: 1, energy: 1.1, desc: "河床露出白骨似的卵石。" },
    { id: "frost", name: "霜降季", days: 50, food: 0.45, water: 0.8, wood: 0.85, energy: 1.2, desc: "夜霜咬住一切会呼吸的东西。" },
  ],

  specialNames: {
    population: "河民",
    happiness: "安定",
    concealment: "隐蔽",
    charge: "锚点充能",
    ember: "余烬",
    fleet: "舰队战力",
  },

  resources: {
    water: { name: "清水", cat: "生存", order: 1, cap: 80, gather: 1.2, gatherName: "汲水", gatherDesc: "从河边捧起陌生却能喝的水。" },
    food: { name: "食物", cat: "生存", order: 2, cap: 80, gather: 1, gatherName: "采集", gatherDesc: "浆果、块茎、以及一些不该问名字的菌。" },
    fiber: { name: "纤维", cat: "生存", order: 3, cap: 60, gather: 1, gatherName: "剥麻", gatherDesc: "河边韧草，可编绳、可铺棚。" },
    wood: { name: "原木", cat: "生存", order: 4, cap: 60, gather: 0.9, gatherName: "拾柴", gatherDesc: "倒木很多。这片林子从不被智子丈量。" },
    stone: { name: "石料", cat: "生存", order: 5, cap: 50, gather: 0.7, gatherName: "采石", gatherDesc: "河边卵石，敲开后有铁锈气味。" },
    ore: { name: "矿石", cat: "工业", order: 6, cap: 40 },
    metal: { name: "金属", cat: "工业", order: 7, cap: 30 },
    energy: { name: "能源", cat: "工业", order: 8, cap: 60 },
    plank: { name: "木板", cat: "工业", order: 9, cap: 50 },
    brick: { name: "砖石", cat: "工业", order: 10, cap: 50 },
    alloy: { name: "合金", cat: "工业", order: 11, cap: 25 },
    fuel: { name: "燃料", cat: "工业", order: 12, cap: 30 },
    knowledge: { name: "知识", cat: "智库", order: 13, cap: 120, gather: 0.6, gatherName: "唤起残档", gatherDesc: "芯片里有人类的全部知识。你只能一次捞起一页。", gatherUnlock: "fire" },
    remnant: { name: "残卷", cat: "智库", order: 14, cap: 40 },
    circuit: { name: "电路", cat: "先进", order: 15, cap: 20 },
    starchart: { name: "星图", cat: "先进", order: 16, cap: 30 },
    antimatter: { name: "反物质", cat: "先进", order: 17, cap: 8 },
    crystal: { name: "时空结晶", cat: "先进", order: 18, cap: 6 },
  },

  buildings: {
    cistern: {
      name: "蓄水坑", tab: "river", era: "生存",
      desc: "在河岸挖坑，铺上纤维。清水开始过夜。",
      cost: { water: 18, fiber: 10 }, ratio: 1.13,
      production: { water: 0.32 }, storage: { water: 90 },
    },
    grove: {
      name: "采集丛", tab: "river", era: "生存",
      desc: "把可食的植物移到营地周围，免得每天走进黑树林。",
      cost: { water: 12, fiber: 14, wood: 6 }, ratio: 1.14,
      production: { food: 0.38, fiber: 0.06 }, storage: { food: 40 },
    },
    fiberShed: {
      name: "纤维棚", tab: "river", era: "生存",
      desc: "晾晒韧草。棚顶漏雨，但够用。",
      cost: { wood: 16, fiber: 12 }, ratio: 1.14,
      production: { fiber: 0.22 }, storage: { fiber: 50 },
    },
    campfire: {
      name: "火塘", tab: "river", era: "生存",
      desc: "第一堆火。夜里，对岸那些眼睛不再靠近。",
      cost: { wood: 20, fiber: 8, stone: 5 }, ratio: 1.2,
      require: { tech: "fire" },
      production: { food: 0.08 },
      flags: { happiness: 4 },
    },
    lumber: {
      name: "林场", tab: "river", era: "聚落",
      desc: "选择倒木，而不是与整片森林为敌。",
      cost: { wood: 28, fiber: 16, stone: 8 }, ratio: 1.15,
      require: { tech: "construction" },
      production: { wood: 0.28 }, storage: { wood: 70 },
    },
    quarry: {
      name: "采石场", tab: "river", era: "聚落",
      desc: "河岸上游的页岩层，敲开后有铁锈气味。",
      cost: { wood: 36, stone: 18, fiber: 10 }, ratio: 1.15,
      require: { tech: "tools" },
      production: { stone: 0.24 }, storage: { stone: 70 },
    },
    hut: {
      name: "棚屋", tab: "river", era: "聚落",
      desc: "两个人类体型的原住民可以挤进去。他们叫这地方“暖洞”。",
      cost: { wood: 22, fiber: 18, stone: 8 }, ratio: 1.16,
      require: { tech: "construction" },
      housing: 2,
    },
    paddy: {
      name: "河滩田", tab: "river", era: "聚落",
      desc: "把洪水变成盟友。芯片里的农书残页忽然变得具体。",
      cost: { wood: 40, fiber: 30, water: 50, stone: 20 }, ratio: 1.15,
      require: { tech: "agriculture" },
      production: { food: 1.05 }, consumption: { water: 0.18 }, storage: { food: 80 },
    },
    silo: {
      name: "粮仓", tab: "river", era: "聚落",
      desc: "霜降季的恐惧有了形状：空仓。",
      cost: { wood: 50, plank: 8, stone: 25 }, ratio: 1.16,
      require: { tech: "agriculture" },
      storage: { food: 180, fiber: 40 },
    },
    warehouse: {
      name: "仓储", tab: "river", era: "聚落",
      desc: "分类、堆叠、记账。文明从不再把东西扔在地上开始。",
      cost: { wood: 60, stone: 40, plank: 12 }, ratio: 1.17,
      require: { tech: "construction" },
      storage: { water: 80, wood: 80, stone: 80, ore: 40, metal: 20, fiber: 40 },
    },
    archive: {
      name: "残档接口", tab: "river", era: "智库",
      desc: "用藤条和卵石给芯片接出第一根“外设”。知识开始外溢。",
      cost: { wood: 28, stone: 12, fiber: 16 }, ratio: 1.15,
      require: { tech: "fire" },
      production: { knowledge: 0.18 }, storage: { knowledge: 220 },
    },
    mine: {
      name: "矿坑", tab: "river", era: "工业",
      desc: "山体里有铁。铁里有地球。",
      cost: { wood: 70, stone: 55, plank: 10 }, ratio: 1.16,
      require: { tech: "mining" },
      production: { ore: 0.2 }, storage: { ore: 60 },
    },
    furnace: {
      name: "冶炼炉", tab: "river", era: "工业",
      desc: "河风灌入炉口。金属第一次在这颗星球上按人类的意志流动。",
      cost: { stone: 80, wood: 40, ore: 20 }, ratio: 1.16,
      require: { tech: "smelting" },
      production: { metal: 0.07 }, consumption: { ore: 0.11, wood: 0.04 }, storage: { metal: 25 },
    },
    mill: {
      name: "水车", tab: "river", era: "工业",
      desc: "河终于开始为你做工。",
      cost: { wood: 90, plank: 20, stone: 40, rope: 0 }, ratio: 1.15,
      require: { tech: "mechanics" },
      production: { energy: 0.35 }, storage: { energy: 50 },
    },
    academy: {
      name: "学堂", tab: "river", era: "智库",
      desc: "教河民辨认地球文字。他们把“三体”念成一种鸟叫。",
      cost: { plank: 28, stone: 60, knowledge: 80, brick: 10 }, ratio: 1.16,
      require: { tech: "writing" },
      production: { knowledge: 0.32 }, storage: { knowledge: 400 },
      flags: { scholarBonus: 0.08 },
    },
    longhouse: {
      name: "长屋", tab: "river", era: "聚落",
      desc: "火塘连成一条。夜里能听见河民学着你的语言做梦。",
      cost: { wood: 80, plank: 25, brick: 20, fiber: 30 }, ratio: 1.17,
      require: { tech: "writing" },
      housing: 5,
      flags: { happiness: 3 },
    },
    observatory: {
      name: "观测台", tab: "river", era: "智库",
      desc: "你终于看见太阳系。地球是一粒将熄的尘。",
      cost: { plank: 40, metal: 20, knowledge: 200, brick: 30 }, ratio: 1.16,
      require: { tech: "mathematics" },
      production: { knowledge: 0.22, starchart: 0.004 }, storage: { knowledge: 600, starchart: 8 },
      flags: { concealment: -0.4 },
    },
    dam: {
      name: "河坝电站", tab: "river", era: "工业",
      desc: "把一条河按住。能量从此不再靠运气。",
      cost: { brick: 40, metal: 35, plank: 30, stone: 100 }, ratio: 1.17,
      require: { tech: "electricity" },
      production: { energy: 1.15 }, storage: { energy: 120 },
    },
    lab: {
      name: "实验室", tab: "river", era: "智库",
      desc: "无菌是一种奢侈。你用沸水和金属近似它。",
      cost: { metal: 40, brick: 35, knowledge: 400, energy: 40 }, ratio: 1.16,
      require: { tech: "electricity" },
      production: { knowledge: 0.55 }, storage: { knowledge: 900 },
    },
    foundry: {
      name: "合金厂", tab: "river", era: "工业",
      desc: "比铁更硬的东西。归乡的龙骨需要它。",
      cost: { metal: 50, brick: 40, energy: 30, stone: 60 }, ratio: 1.17,
      require: { tech: "steel" },
      production: { alloy: 0.05 }, consumption: { metal: 0.08, energy: 0.12 }, storage: { alloy: 20 },
    },
    solar: {
      name: "光伏阵", tab: "river", era: "工业",
      desc: "这颗恒星比太阳略偏橙。芯片里的曲线仍能用。",
      cost: { alloy: 15, circuit: 6, metal: 30 }, ratio: 1.16,
      require: { tech: "electronics" },
      production: { energy: 0.85 }, storage: { energy: 80 },
    },
    factory: {
      name: "装配厂", tab: "river", era: "工业",
      desc: "流水线。河民第一次看见“重复”变成力量。",
      cost: { alloy: 20, brick: 50, metal: 40, circuit: 4 }, ratio: 1.18,
      require: { tech: "electronics" },
      production: { circuit: 0.012 }, consumption: { alloy: 0.02, energy: 0.2 },
      flags: { craftBonus: 0.1 },
    },
    clonevat: {
      name: "培育舱", tab: "river", era: "先进",
      desc: "义体技术的远亲。不是繁殖，是续写。",
      cost: { alloy: 25, circuit: 12, knowledge: 800, energy: 80 }, ratio: 1.18,
      require: { tech: "computing" },
      housing: 8,
    },
    reactor: {
      name: "裂变堆", tab: "river", era: "先进",
      desc: "把一颗小太阳关进河岸的水泥里。导师会骂你，也会点头。",
      cost: { alloy: 40, circuit: 18, metal: 80, remnant: 10 }, ratio: 1.2,
      require: { tech: "nuclear" },
      production: { energy: 3.2, antimatter: 0.001 }, consumption: { ore: 0.15 }, storage: { energy: 200, antimatter: 3 },
      flags: { concealment: -1.2 },
    },
    pad: {
      name: "发射坪", tab: "space", era: "星空",
      desc: "第一枚箭矢指向地球曾经的方向。烟柱会说话，但愿智子听不见。",
      cost: { alloy: 30, fuel: 20, circuit: 8, brick: 40 }, ratio: 1.18,
      require: { tech: "rocketry" },
      production: { fleet: 0.06, starchart: 0.01 }, consumption: { fuel: 0.05, energy: 0.3 },
      flags: { concealment: -2.2 },
    },
    dock: {
      name: "轨道船坞", tab: "space", era: "星空",
      desc: "在没有月亮的夜空里，多出一座人造的。",
      cost: { alloy: 50, circuit: 20, fuel: 30, starchart: 8 }, ratio: 1.2,
      require: { tech: "orbital" },
      production: { fleet: 0.22 }, consumption: { energy: 0.8, alloy: 0.03 },
      flags: { concealment: -1.5 },
    },
    jammer: {
      name: "智子干扰塔", tab: "space", era: "星空",
      desc: "导师留下的禁术：不是战胜智子，是让它们在这里“近视”。",
      cost: { alloy: 35, circuit: 25, remnant: 15, knowledge: 2000 }, ratio: 1.22,
      require: { tech: "sophon" },
      flags: { concealment: 6, concealRegen: 0.35 },
    },
    anchorArray: {
      name: "锚点阵列", tab: "anchor", era: "时间",
      desc: "把河边那一秒钟放大。充能时，空气会像要裂开。",
      cost: { alloy: 20, circuit: 10, crystal: 1, energy: 100 }, ratio: 1.2,
      require: { tech: "timeanchor" },
      production: { charge: 0.035, crystal: 0.0008 }, consumption: { energy: 0.4 },
    },
    drive: {
      name: "曲率环", tab: "space", era: "归乡",
      desc: "回家的门。门后是2300年的地球，以及已经到达的舰队。",
      cost: { alloy: 80, circuit: 40, antimatter: 4, crystal: 3, fleet: 0 }, ratio: 1.25,
      require: { tech: "curvature" },
      production: { fleet: 1.1 }, consumption: { antimatter: 0.002, energy: 2 },
      flags: { concealment: -3 },
    },
  },

  jobs: {
    forager: {
      name: "采集者",
      desc: "在河滩与林缘之间走一条不会迷路的路。",
      production: { food: 0.16, fiber: 0.05 },
      require: {},
    },
    cutter: {
      name: "伐木工",
      desc: "只砍已标记的树。河民比你更怕林子里的东西。",
      production: { wood: 0.14 },
      require: { tech: "construction" },
    },
    mason: {
      name: "石工",
      desc: "锤声成为聚落的第二种心跳。",
      production: { stone: 0.11 },
      require: { tech: "tools" },
    },
    miner: {
      name: "矿工",
      desc: "地下没有智子。他们喜欢这一点。",
      production: { ore: 0.09, stone: 0.03 },
      require: { tech: "mining" },
    },
    decoder: {
      name: "解码者",
      desc: "对着空气朗读芯片里的句子，直到句子变成工具。",
      production: { knowledge: 0.13 },
      require: { tech: "writing" },
    },
    operator: {
      name: "司炉",
      desc: "盯着火，也盯着温度。金属讨厌走神的人。",
      production: { metal: 0.035, energy: 0.06 },
      require: { tech: "smelting" },
    },
    technician: {
      name: "技术员",
      desc: "把地球的电路图翻译成这颗星球能懂的语言。",
      production: { circuit: 0.006, energy: 0.04 },
      require: { tech: "electronics" },
    },
    keeper: {
      name: "守锚人",
      desc: "坐在河边，确认这一刻仍可被返回。",
      production: { charge: 0.01 },
      flags: { happiness: 0.8 },
      require: { tech: "timeanchor" },
    },
  },

  techs: {
    fire: {
      name: "用火", era: "生存", order: 1,
      desc: "湿木、火花、以及义体里残存的点火程序。夜被推开一寸。",
      cost: { wood: 15, fiber: 8, food: 8 },
      unlocks: "火塘、残档接口。知识开始可被唤起。",
    },
    survival: {
      name: "生存学", era: "生存", order: 2,
      desc: "芯片打开《野外生存》的第一页。纸不存在，字直接烙在视野上。",
      cost: { knowledge: 20, food: 20 },
      require: { tech: "fire" },
      unlocks: "采集效率提升。",
      flags: { gatherBonus: 0.25 },
    },
    construction: {
      name: "构架", era: "生存", order: 3,
      desc: "梁、柱、斜撑。棚屋不再只是“靠在一起的木头”。",
      cost: { knowledge: 35, wood: 30, fiber: 20 },
      require: { tech: "fire" },
      unlocks: "棚屋、林场、仓储。",
    },
    tools: {
      name: "工具", era: "生存", order: 4,
      desc: "刃口改变物种的命运。你把这句话讲给河民听，他们把石头磨得更好。",
      cost: { knowledge: 50, wood: 25, stone: 20 },
      require: { tech: "construction" },
      unlocks: "采石场、石工。",
    },
    agriculture: {
      name: "农耕", era: "聚落", order: 5,
      desc: "不要跟随浆果，要让浆果跟随你。",
      cost: { knowledge: 70, food: 40, water: 40, fiber: 25 },
      require: { tech: "survival" },
      unlocks: "河滩田、粮仓。",
    },
    mining: {
      name: "采矿", era: "聚落", order: 6,
      desc: "地球的工业革命在一处河岸被重新点燃，规模小得可笑，意义不是。",
      cost: { knowledge: 120, stone: 40, wood: 40 },
      require: { tech: "tools" },
      unlocks: "矿坑、矿工。",
    },
    smelting: {
      name: "冶炼", era: "工业", order: 7,
      desc: "矿石承认自己内部藏着另一种形状。",
      cost: { knowledge: 180, ore: 25, stone: 50, wood: 30 },
      require: { tech: "mining" },
      unlocks: "冶炼炉、司炉、金属。",
    },
    writing: {
      name: "残档编目", era: "智库", order: 8,
      desc: "知识若不被编目，就只是胸腔里的噪音。",
      cost: { knowledge: 160, wood: 40, fiber: 30 },
      require: { tech: "survival" },
      unlocks: "学堂、长屋、解码者、工坊残卷。",
    },
    mathematics: {
      name: "数学", era: "智库", order: 9,
      desc: "导师曾说：三体人能锁死物理，却锁不死你在河边用树枝画的圆。",
      cost: { knowledge: 280, remnant: 1 },
      require: { tech: "writing" },
      unlocks: "观测台。",
    },
    mechanics: {
      name: "机械", era: "工业", order: 10,
      desc: "齿轮比肌肉诚实。",
      cost: { knowledge: 320, metal: 15, plank: 20, wood: 50 },
      require: { tech: "smelting" },
      unlocks: "水车。",
    },
    irrigation: {
      name: "水利", era: "聚落", order: 11,
      desc: "你开始管理一条河，而不仅仅是向它乞水。",
      cost: { knowledge: 240, water: 80, stone: 60 },
      require: { tech: "agriculture" },
      unlocks: "清水产出提升。",
      flags: { waterProd: 0.2 },
    },
    electricity: {
      name: "电力", era: "工业", order: 12,
      desc: "黑暗被重新定义。义体第一次感到“故乡的电流”。",
      cost: { knowledge: 520, metal: 30, energy: 40 },
      require: { tech: "mechanics" },
      unlocks: "河坝电站、实验室。",
    },
    chemistry: {
      name: "化学", era: "工业", order: 13,
      desc: "把物质拆开再组装。燃料有了名字。",
      cost: { knowledge: 700, ore: 40, food: 60, energy: 30 },
      require: { tech: "electricity" },
      unlocks: "燃料精炼。",
    },
    steel: {
      name: "合金工艺", era: "工业", order: 14,
      desc: "铁的孩子。比父辈更适合离开地面。",
      cost: { knowledge: 900, metal: 50, energy: 50 },
      require: { tech: "chemistry" },
      unlocks: "合金厂。",
    },
    electronics: {
      name: "电子", era: "先进", order: 15,
      desc: "芯片终于遇见了它在这颗星球上的亲戚。",
      cost: { knowledge: 1400, metal: 40, remnant: 4, energy: 80 },
      require: { tech: "electricity" },
      unlocks: "光伏、装配厂、技术员、电路。",
    },
    computing: {
      name: "计算重构", era: "先进", order: 16,
      desc: "你把人类的计算机科学从沙盘里重新砌起来。速度很慢。足够。",
      cost: { knowledge: 2200, circuit: 8, remnant: 6 },
      require: { tech: "electronics" },
      unlocks: "培育舱。",
    },
    rocketry: {
      name: "推进", era: "星空", order: 17,
      desc: "第一枚火箭。它不会拯救地球，但它证明方向存在。",
      cost: { knowledge: 3000, fuel: 20, alloy: 15, starchart: 3 },
      require: { tech: "steel" },
      unlocks: "发射坪、星空页签。",
    },
    orbital: {
      name: "轨道", era: "星空", order: 18,
      desc: "离开地面之后，河声消失。你这才意识到自己有多想念它。",
      cost: { knowledge: 4500, starchart: 8, alloy: 25, circuit: 12 },
      require: { tech: "rocketry" },
      unlocks: "轨道船坞。",
    },
    nuclear: {
      name: "核", era: "先进", order: 19,
      desc: "面壁者曾用过更疯狂的东西。你只要一座安分的堆。",
      cost: { knowledge: 6000, alloy: 30, remnant: 10, energy: 200 },
      require: { tech: "computing" },
      unlocks: "裂变堆、微量反物质。",
    },
    sophon: {
      name: "智子理论", era: "星空", order: 20,
      desc: "二维展开的宇宙探针。这里仍是盲区——只要你不朝地球大声说话。",
      cost: { knowledge: 7500, starchart: 12, remnant: 12, circuit: 15 },
      require: { tech: "orbital" },
      unlocks: "智子干扰塔。理解隐蔽。",
    },
    relativity: {
      name: "相对论残篇", era: "时间", order: 21,
      desc: "时间不是河。时间是你可以抛锚的海。",
      cost: { knowledge: 5000, remnant: 8 },
      require: { tech: "mathematics" },
      unlocks: "时空结晶的理论门槛。",
    },
    timeanchor: {
      name: "锚点原理", era: "时间", order: 22,
      desc: "导师把名字说完了：锚，是为了回去；时间，是为了再走一次。",
      cost: { knowledge: 9000, remnant: 15, energy: 250, crystal: 1 },
      require: { tech: "relativity" },
      unlocks: "锚点阵列、守锚人、回溯。",
    },
    darkforest: {
      name: "黑暗森林", era: "星空", order: 23,
      desc: "宇宙是一座黑暗森林。你在林中点了一堆必须被看见的火。",
      cost: { knowledge: 10000, starchart: 16, remnant: 10 },
      require: { tech: "sophon" },
      unlocks: "舰队效率提升，隐蔽消耗降低。",
      flags: { fleetBonus: 0.2, concealRelief: 0.25 },
    },
    curvature: {
      name: "曲率航行", era: "归乡", order: 24,
      desc: "把空间折起来。地球不再是一个无法抵达的点。",
      cost: { knowledge: 14000, antimatter: 3, crystal: 2, starchart: 20 },
      require: { tech: "timeanchor" },
      unlocks: "曲率环。",
    },
    deterrence: {
      name: "威慑", era: "归乡", order: 25,
      desc: "拯救不一定是战胜。也可以是让对方不敢落下第二只靴子。",
      cost: { knowledge: 16000, fleet: 40, antimatter: 2, remnant: 20 },
      require: { tech: "curvature" },
      unlocks: "干预准备度大幅提升。",
      flags: { readyBonus: 25 },
    },
    homecoming: {
      name: "归乡", era: "归乡", order: 26,
      desc: "坐标锁定：太阳系。时间锁定：舰队抵达的那一日。你将带着一条河的文明回去。",
      cost: { knowledge: 20000, fleet: 80, crystal: 4, antimatter: 5, remnant: 25 },
      require: { tech: "deterrence" },
      unlocks: "启动跃迁，尝试拯救地球。",
    },
  },

  crafts: {
    plank: {
      name: "木板",
      desc: "把树变成面。房屋与船都从这一步开始。",
      require: { tech: "construction" },
      cost: { wood: 5 },
      gain: { plank: 1 },
    },
    rope: {
      name: "绳索",
      desc: "纤维的军队。",
      require: { tech: "tools" },
      cost: { fiber: 4 },
      gain: { fiber: 0 },
      extra: true,
    },
    brick: {
      name: "砖石",
      desc: "火与土的契约。",
      require: { tech: "smelting" },
      cost: { stone: 3, water: 1, wood: 1 },
      gain: { brick: 1 },
    },
    metalCraft: {
      name: "手工炼金",
      desc: "炉子不够时，用更原始的方法。",
      require: { tech: "smelting" },
      cost: { ore: 4, wood: 2 },
      gain: { metal: 1 },
    },
    alloy: {
      name: "锻造合金",
      desc: "反复折叠，直到它记得地球的标准。",
      require: { tech: "steel" },
      cost: { metal: 3, energy: 2 },
      gain: { alloy: 1 },
    },
    fuel: {
      name: "精炼燃料",
      desc: "从植物与矿脉里挤出离开地面的资格。",
      require: { tech: "chemistry" },
      cost: { fiber: 6, ore: 2, energy: 2 },
      gain: { fuel: 1 },
    },
    remnant: {
      name: "装订残卷",
      desc: "把芯片里的一章按在木板上。学堂需要可以触摸的记忆。",
      require: { tech: "writing" },
      cost: { knowledge: 60, plank: 2, fiber: 4 },
      gain: { remnant: 1 },
    },
    circuit: {
      name: "蚀刻电路",
      desc: "手会抖。抖也要刻。",
      require: { tech: "electronics" },
      cost: { alloy: 2, knowledge: 40, energy: 3 },
      gain: { circuit: 1 },
    },
    starchart: {
      name: "测绘星图",
      desc: "每一张图都在问：地球还在吗？",
      require: { tech: "mathematics" },
      cost: { knowledge: 120, remnant: 1 },
      gain: { starchart: 1 },
    },
    crystal: {
      name: "凝结时空结晶",
      desc: "锚点充能溢出时，河边的沙子会变成这种东西。",
      require: { tech: "relativity" },
      cost: { energy: 80, knowledge: 200, remnant: 2 },
      gain: { crystal: 1 },
    },
    antimatter: {
      name: "约束反物质",
      desc: "用磁场抱住一滴会吞掉世界的露水。",
      require: { tech: "nuclear" },
      cost: { energy: 150, alloy: 4, circuit: 2 },
      gain: { antimatter: 1 },
    },
  },

  upgrades: {
    sharpFlint: {
      name: "燧石刃",
      desc: "采集、剥麻、拾柴效率 +25%。",
      require: { tech: "tools" },
      cost: { stone: 30, fiber: 20, knowledge: 40 },
      flags: { gatherBonus: 0.25 },
    },
    cropRotate: {
      name: "轮作",
      desc: "食物建筑产出 +20%。",
      require: { tech: "agriculture" },
      cost: { food: 80, knowledge: 100, water: 50 },
      flags: { foodProd: 0.2 },
    },
    pulley: {
      name: "滑轮组",
      desc: "原木与石料建筑产出 +20%。",
      require: { tech: "mechanics" },
      cost: { plank: 20, fiber: 40, knowledge: 200 },
      flags: { woodStoneProd: 0.2 },
    },
    bellows: {
      name: "鼓风",
      desc: "金属产出 +30%。",
      require: { tech: "smelting" },
      cost: { wood: 60, fiber: 30, knowledge: 180 },
      flags: { metalProd: 0.3 },
    },
    catalog: {
      name: "残档压缩",
      desc: "知识产出 +25%，知识上限 +20%。",
      require: { tech: "writing" },
      cost: { remnant: 3, knowledge: 300, plank: 15 },
      flags: { knowledgeProd: 0.25, knowledgeCap: 0.2 },
    },
    silentBus: {
      name: "静默总线",
      desc: "建筑造成的隐蔽损耗 -35%。",
      require: { tech: "electronics" },
      cost: { circuit: 6, remnant: 5, knowledge: 800 },
      flags: { concealRelief: 0.35 },
    },
    assembly: {
      name: "标准件",
      desc: "工坊每次额外获得 1 个产物（按比例）。",
      require: { tech: "electronics" },
      cost: { circuit: 8, alloy: 20, knowledge: 1000 },
      flags: { extraCraft: 0.5 },
    },
    autoCraft: {
      name: "自动装配",
      desc: "每秒自动尝试制作木板、砖石、燃料。",
      require: { tech: "computing" },
      cost: { circuit: 12, alloy: 25, knowledge: 1800 },
      flags: { autoCraft: true },
    },
    deepMine: {
      name: "深井",
      desc: "矿石产出 +40%。",
      require: { tech: "mining" },
      cost: { metal: 20, wood: 80, knowledge: 400 },
      flags: { oreProd: 0.4 },
    },
    hydroTune: {
      name: "水轮机叶片",
      desc: "能源产出 +25%。",
      require: { tech: "electricity" },
      cost: { metal: 25, plank: 20, knowledge: 500 },
      flags: { energyProd: 0.25 },
    },
    darkProtocol: {
      name: "黑暗协议",
      desc: "舰队产出 +15%，隐蔽再生 +0.2/秒。",
      require: { tech: "darkforest" },
      cost: { starchart: 10, circuit: 10, remnant: 8 },
      flags: { fleetBonus: 0.15, concealRegen: 0.2 },
    },
  },

  metaphysics: {
    muscle: {
      name: "肌肉记忆",
      desc: "每次手动采集产量 +100%。回溯后仍记得手怎么动。",
      cost: 8,
      flags: { gatherBonus: 1 },
    },
    echo: {
      name: "河岸回响",
      desc: "新的一轮开局即拥有 1 座蓄水坑与 1 座采集丛。",
      cost: 15,
      flags: { startBuildings: { cistern: 1, grove: 1 } },
    },
    decode: {
      name: "加速解码",
      desc: "知识产出 +30%。",
      cost: 22,
      flags: { knowledgeProd: 0.3 },
    },
    cache: {
      name: "仓储直觉",
      desc: "所有资源上限 +35%。",
      cost: 28,
      flags: { allCap: 0.35 },
    },
    veil: {
      name: "隐蔽协议",
      desc: "隐蔽基础值 +20，损耗 -20%。",
      cost: 36,
      flags: { concealBase: 20, concealRelief: 0.2 },
    },
    reactor: {
      name: "余烬反应",
      desc: "全局产出 +12%。",
      cost: 48,
      flags: { globalProd: 0.12 },
    },
    mentor: {
      name: "导师残响",
      desc: "开局即掌握用火、生存学与构架。",
      cost: 64,
      flags: { startTechs: ["fire", "survival", "construction"] },
    },
    heartbeat: {
      name: "第二次心跳",
      desc: "锚点充能速度 +80%。",
      cost: 80,
      flags: { chargeBonus: 0.8 },
    },
  },

  intro: [
    "白光褪去之后，先听见的是河。\n\n不是地球的河。水声更沉，像有什么巨大的东西在上游缓慢翻身。\n你躺在湿冷的卵石上，义体关节还在报错，胸腔里那枚芯片却已经醒了。",
    "导师的声音从骨头里渗出来，沙哑，像是录了不止一次。\n\n「如果你能听见……说明传送成功。」\n「三体舰队已经到了土星轨道。地球没有胜算。」\n「投降协议会在2300年写完最后一行。」",
    "「时间之锚不是诗。它是一个坐标。」\n「这个河边，这个时刻——只要装置充能完毕，你永远可以回来。」\n「芯片里装着人类全部的知识。但知识不能当面包吃。」\n「你得重新把文明从泥里抠出来。」",
    "「这里没有智子。他们看不见。这是我们最后的盲区。」\n「去探索。去创造。去发展。」\n「然后在2300年真正落下之前——把地球抢回来。」\n\n风从对岸的黑树林里穿过来。\n有低矮的生物在灌木后张望，眼睛像两粒未打磨的石头。\n你坐起来。河水冰凉，星空陌生。\n胸腔里，时间之锚轻轻跳了一下。",
  ],

  stories: [
    { id: "wake", trigger: {}, text: "你还记得自己的名字。义体的序列号在视野角落闪烁。河水的味道像含铁的雨。" },
    { id: "firstFire", trigger: { tech: "fire" }, text: "火升起来的时候，对岸有什么东西发出一声短促的鸣叫，随后退进树影。导师没在录音里提过它们。" },
    { id: "firstHut", trigger: { building: "hut", count: 1 }, text: "棚屋立住的第一夜，三名河民走来。他们把食物放在门口，又把一块打磨过的石头放在你掌心。像是租约。" },
    { id: "archive", trigger: { building: "archive", count: 1 }, text: "残档接口接通的瞬间，两千年的农书、几何与一首没唱完的歌同时涌进来。你吐了。然后开始分类。" },
    { id: "folk", trigger: { pop: 5 }, text: "河民开始模仿你的作息。他们仍不会制造轮子，但已经会把工具放回原处。低智慧，不是无智慧。" },
    { id: "metal", trigger: { tech: "smelting" }, text: "第一块金属凝固时，你看见了自己的脸。义体的外壳在这颗星球上第一次有了镜子。" },
    { id: "stars", trigger: { building: "observatory", count: 1 }, text: "地球的光谱还在。它还没被改写成三体的恒星。你把这件事写进日志，手有些抖。" },
    { id: "radio", trigger: { tech: "electronics" }, text: "你造出了无线电，又立刻把它关掉。盲区的第一条法则：不要朝黑暗森林挥手。" },
    { id: "sophon", trigger: { tech: "sophon" }, text: "智子理论被重新推演完毕。结论与导师相同：这颗星球仍是影子。但发射、跃迁、广播——都会在宇宙里划火柴。" },
    { id: "anchor", trigger: { tech: "timeanchor" }, text: "你终于听懂时间之锚的名字。回去不是逃跑。回去是把一条已经走通的路，走得更狠。" },
    { id: "fleet", trigger: { tech: "rocketry" }, text: "火箭离地。河面被光切成两半。河民捂住耳朵，却全部仰头。他们不知道地球，但知道你要去很远的地方。" },
    { id: "home", trigger: { tech: "homecoming" }, text: "归乡坐标写入曲率环。2300年的地球在另一头等你——投降仪式、舰队、以及仍未熄灭的人类。" },
  ],

  events: [
    { id: "flood", minDay: 8, weight: 3, text: "夜洪把上游的浮木与湿润的块茎冲到营地。", gain: { wood: 18, food: 12, water: 25 } },
    { id: "gift", minDay: 15, weight: 2, text: "河民留下一堆纤维和打磨石。他们仍不进屋，只在火光外蹲着看。", gain: { fiber: 16, stone: 10 }, requirePop: 1 },
    { id: "chip", minDay: 20, weight: 2, text: "芯片自行解压出一页被损坏的笔记：导师的字迹，写着“先活下来”。", gain: { knowledge: 25 } },
    { id: "oreVein", minDay: 40, weight: 2, text: "霜降后山体裂开一道口。矿脉像伤口一样亮。", gain: { ore: 14, stone: 12 }, require: { tech: "mining" } },
    { id: "drought", minDay: 30, weight: 2, text: "连续无雨。蓄水坑的水位露出泥线。", lose: { water: 20 }, warn: true },
    { id: "festival", minDay: 50, weight: 1, text: "丰叶季的夜里，河民围着火塘发出一种整齐的喉音。安定回升。", happiness: 8, requirePop: 4 },
    { id: "flicker", minDay: 120, weight: 1, text: "观测台捕捉到一次极短的智子式扰动，随即消失。像有人在宇宙外侧看了你们一眼。", concealment: -8, require: { tech: "mathematics" }, warn: true },
    { id: "emberDream", minDay: 10, weight: 1, text: "你梦见自己再次躺在河边。醒来时掌心有一粒不存在的沙。锚点在听。", gain: { charge: 4 } },
    { id: "comet", minDay: 80, weight: 1, text: "一颗没有编目的彗星划过。星图自动补了一笔。", gain: { starchart: 2, knowledge: 40 }, require: { tech: "mathematics" } },
  ],
};

// mill cost had a dummy rope:0 — crafts.rope currently grants nothing useful.
// Fix mill to not require rope; keep rope craft as a fiber sink that grants a hidden bonus item.
TA.DATA.buildings.mill.cost = { wood: 90, plank: 20, stone: 40 };
TA.DATA.crafts.rope = {
  name: "绳索",
  desc: "纤维的军队。用于加固建筑（全局上限 +1%/次，最多 +20%）。",
  require: { tech: "tools" },
  cost: { fiber: 5 },
  gain: {},
  flags: { ropeCap: 0.01 },
};
TA.DATA.buildings.drive.cost = { alloy: 80, circuit: 40, antimatter: 4, crystal: 3 };
