window.TA = window.TA || {};

TA.DATA = {
  seasons: [
    { id: "tide", name: "潮汐季", days: 50, food: 1.1, water: 1.25, wood: 1, energy: 1, desc: "河水上涨，汲取更容易。" },
    { id: "bloom", name: "丰叶季", days: 50, food: 1.35, water: 1, wood: 1.2, energy: 1, desc: "对岸的林莽疯长，浆果坠满枝头。" },
    { id: "dry", name: "干裂季", days: 50, food: 0.85, water: 0.65, wood: 1, energy: 1.1, desc: "河床露出白骨似的卵石。" },
    { id: "frost", name: "霜降季", days: 50, food: 0.45, water: 0.8, wood: 0.85, energy: 1.2, desc: "夜霜咬住一切会呼吸的生命。" },
  ],

  specialNames: {
    population: "居民",
    happiness: "安定",
    concealment: "隐蔽",
    charge: "锚点充能",
    ember: "余烬",
    fleet: "舰队战力",
  },

  resources: {
    water: { name: "清水", cat: "生存", order: 1, cap: 80, gather: 1.2, gatherName: "汲水", gatherDesc: "从河边捧起陌生却能饮用的清水。" },
    food: { name: "食物", cat: "生存", order: 2, cap: 80, gather: 1, gatherName: "采集", gatherDesc: "浆果、块茎、以及一些不该询问名字的菌类。" },
    meal: { name: "熟食", cat: "生存", order: 2.2, cap: 50, seeUnlock: "cookery" },
    meat: { name: "兽肉", cat: "生存", order: 2.4, cap: 40, seeUnlock: "husbandry" },
    fiber: { name: "纤维", cat: "生存", order: 3, cap: 60, gather: 1, gatherName: "剥麻", gatherDesc: "河边韧草，可以编成绳索、可以铺成棚顶。" },
    hide: { name: "皮革", cat: "生存", order: 3.2, cap: 40, seeUnlock: "husbandry" },
    cloth: { name: "布匹", cat: "生存", order: 3.4, cap: 40, seeUnlock: "weaving" },
    wood: { name: "原木", cat: "生存", order: 4, cap: 60, gather: 0.9, gatherName: "拾柴", gatherDesc: "倒木很多。这片林子从不被智子丈量。" },
    stone: { name: "石料", cat: "生存", order: 5, cap: 50, gather: 0.7, gatherName: "采石", gatherDesc: "河边卵石，敲开后有铁锈气味。" },
    ore: { name: "矿石", cat: "工业", order: 6, cap: 40 },
    metal: { name: "金属", cat: "工业", order: 7, cap: 30 },
    energy: { name: "能源", cat: "工业", order: 8, cap: 60 },
    plank: { name: "木板", cat: "工业", order: 9, cap: 50 },
    brick: { name: "砖石", cat: "工业", order: 10, cap: 50 },
    alloy: { name: "合金", cat: "工业", order: 11, cap: 25 },
    fuel: { name: "燃料", cat: "工业", order: 12, cap: 30 },
    knowledge: { name: "知识", cat: "智库", order: 13, cap: 120, gather: 0.6, gatherName: "唤起残档", gatherDesc: "芯片里有人类的全部知识。你只能一次捞起一页残档。", gatherUnlock: "fire" },
    remnant: { name: "残卷", cat: "智库", order: 14, cap: 40 },
    circuit: { name: "电路", cat: "先进", order: 15, cap: 20 },
    starchart: { name: "星图", cat: "先进", order: 16, cap: 30 },
    antimatter: { name: "反物质", cat: "先进", order: 17, cap: 8 },
    crystal: { name: "时空结晶", cat: "先进", order: 18, cap: 6 },
  },

  buildings: {
    cistern: {
      name: "蓄水坑", tab: "river", era: "生存",
      desc: "在河岸挖掘水坑，铺上纤维。清水开始隔夜存放。",
      cost: { water: 18, fiber: 10 }, ratio: 1.13,
      production: { water: 0.32 }, storage: { water: 90 },
    },
    grove: {
      name: "采集丛", tab: "river", era: "生存",
      desc: "把可食的植物移到营地周围。",
      cost: { water: 12, fiber: 14, wood: 6 }, ratio: 1.14,
      production: { food: 0.38, fiber: 0.06 }, storage: { food: 40 },
    },
    fiberShed: {
      name: "纤维棚", tab: "river", era: "生存",
      desc: "晾晒韧草。棚顶仍会漏雨。",
      cost: { wood: 16, fiber: 12 }, ratio: 1.14,
      production: { fiber: 0.22 }, storage: { fiber: 50 },
    },
    loom: {
      name: "织机", tab: "river", era: "聚落",
      desc: "经线与纬线。纤维第一次承认自己可以成为衣服。",
      cost: { wood: 36, fiber: 24, stone: 8 }, ratio: 1.15,
      require: { tech: "weaving" },
      production: { cloth: 0.07 }, consumption: { fiber: 0.16, hide: 0.03 }, storage: { cloth: 25 },
    },
    clothShed: {
      name: "布仓", tab: "river", era: "聚落",
      desc: "布匹怕潮、怕虫。离地、封口、记账。",
      cost: { wood: 32, plank: 8, fiber: 16 }, ratio: 1.15,
      require: { tech: "weaving" },
      storage: { cloth: 80, fiber: 40, hide: 20 },
    },
    tailor: {
      name: "缝衣间", tab: "river", era: "聚落",
      desc: "把布匹变成可以穿的形状。居民第一次感觉自己被文明盖住。",
      cost: { wood: 28, cloth: 6, fiber: 18 }, ratio: 1.16,
      require: { tech: "weaving" },
      consumption: { cloth: 0.04 },
      flags: { happiness: 6 },
    },
    campfire: {
      name: "火塘", tab: "river", era: "生存",
      desc: "第一堆火焰。夜晚，对岸那些眼睛不再靠近。",
      cost: { wood: 20, fiber: 8, stone: 5 }, ratio: 1.2,
      require: { tech: "fire" },
      production: { food: 0.08 },
      flags: { happiness: 4 },
    },
    kitchen: {
      name: "灶台", tab: "river", era: "生存",
      desc: "把生食按住，让火焰完成其余的工作。熟食让人愿意留下来。",
      cost: { wood: 30, stone: 18, fiber: 12 }, ratio: 1.16,
      require: { tech: "cookery" },
      production: { meal: 0.24 }, consumption: { food: 0.16, meat: 0.05, water: 0.08 }, storage: { meal: 40 },
      flags: { happiness: 5 },
    },
    smokehouse: {
      name: "熏棚", tab: "river", era: "聚落",
      desc: "烟把兽肉变成可以过冬的东西。霜降季因此短了一截。",
      cost: { wood: 34, fiber: 14, stone: 10 }, ratio: 1.16,
      require: { tech: "cookery" },
      production: { meal: 0.14, food: 0.03 }, consumption: { meat: 0.1, wood: 0.05 }, storage: { meal: 50, meat: 20 },
    },
    lumber: {
      name: "林场", tab: "river", era: "聚落",
      desc: "选择倒木。不要与整片森林为敌。",
      cost: { wood: 28, fiber: 16, stone: 8 }, ratio: 1.15,
      require: { tech: "construction" },
      production: { wood: 0.28 }, storage: { wood: 70, plank: 20 },
    },
    sawmill: {
      name: "锯木棚", tab: "river", era: "聚落",
      desc: "把原木剖开。平面从此可以叠放、可以钉合。",
      cost: { wood: 40, stone: 16, fiber: 12 }, ratio: 1.15,
      require: { tech: "forestry" },
      production: { plank: 0.05 }, consumption: { wood: 0.22 }, storage: { plank: 35 },
    },
    charcoalPit: {
      name: "炭窑", tab: "river", era: "聚落",
      desc: "让原木在缺氧里变成更听话的火焰。",
      cost: { wood: 36, stone: 20, fiber: 10 }, ratio: 1.16,
      require: { tech: "forestry" },
      production: { energy: 0.14 }, consumption: { wood: 0.16 },
    },
    nursery: {
      name: "苗圃", tab: "river", era: "聚落",
      desc: "先种下明天的原木。林场从此不必只向倒木伸手。",
      cost: { wood: 24, water: 30, fiber: 18 }, ratio: 1.15,
      require: { tech: "forestry" },
      production: { wood: 0.18, fiber: 0.04 }, consumption: { water: 0.05 }, storage: { wood: 40 },
    },
    quarry: {
      name: "采石场", tab: "river", era: "聚落",
      desc: "河岸上游的页岩层，敲开后有铁锈气味。",
      cost: { wood: 36, stone: 18, fiber: 10 }, ratio: 1.15,
      require: { tech: "tools" },
      production: { stone: 0.24 }, storage: { stone: 70, brick: 20 },
    },
    hut: {
      name: "棚屋", tab: "river", era: "聚落",
      desc: "两个人类体型的原住民可以挤进去。他们叫这地方「暖洞」。",
      cost: { wood: 22, fiber: 18, stone: 8 }, ratio: 1.16,
      require: { tech: "construction" },
      housing: 2,
    },
    guestHut: {
      name: "专属厢房", tab: "river", era: "聚落",
      desc: "一间只给抽签而来的人住的屋子。门槛比棚屋更高。",
      cost: { wood: 56, fiber: 34, stone: 26, plank: 12 }, ratio: 1.18,
      require: { tech: "construction" },
      housingElite: 1,
    },
    paddy: {
      name: "河滩田", tab: "river", era: "聚落",
      desc: "把洪水变成盟友。芯片里的农书残页忽然变得具体。",
      cost: { wood: 40, fiber: 30, water: 50, stone: 20 }, ratio: 1.15,
      require: { tech: "agriculture" },
      production: { food: 1.05 }, consumption: { water: 0.18 }, storage: { food: 80 },
    },
    orchard: {
      name: "果园", tab: "river", era: "聚落",
      desc: "把浆果固定在营地能看见的距离里。",
      cost: { wood: 36, fiber: 24, water: 40, food: 20 }, ratio: 1.15,
      require: { tech: "agriculture" },
      production: { food: 0.55, fiber: 0.04 }, consumption: { water: 0.1 }, storage: { food: 50 },
    },
    well: {
      name: "水井", tab: "river", era: "聚落",
      desc: "向下要清水，而不是只向河流伸手。",
      cost: { stone: 40, wood: 24, fiber: 16 }, ratio: 1.15,
      require: { tech: "irrigation" },
      production: { water: 0.55 }, storage: { water: 80 },
    },
    pen: {
      name: "畜栏", tab: "river", era: "聚落",
      desc: "把会跑的食物围住。兽肉与皮革开始按节奏出现。",
      cost: { wood: 40, fiber: 28, food: 20 }, ratio: 1.16,
      require: { tech: "husbandry" },
      production: { meat: 0.22, hide: 0.07 }, consumption: { food: 0.14 },
      flags: { happiness: 1 },
    },
    pasture: {
      name: "牧地", tab: "river", era: "聚落",
      desc: "清水换成兽肉、纤维与皮革。河岸第一次听见牲畜的叫声。",
      cost: { wood: 32, fiber: 22, water: 40 }, ratio: 1.15,
      require: { tech: "husbandry" },
      production: { meat: 0.12, fiber: 0.1, hide: 0.03 }, consumption: { water: 0.1 },
    },
    tannery: {
      name: "鞣皮棚", tab: "river", era: "聚落",
      desc: "皮革怕腐烂。清水、荫凉、以及足够的耐心。",
      cost: { wood: 28, fiber: 16, stone: 12 }, ratio: 1.15,
      require: { tech: "husbandry" },
      storage: { hide: 70, meat: 20 },
    },
    silo: {
      name: "粮仓", tab: "river", era: "聚落",
      desc: "霜降季的恐惧有了形状：空仓。",
      cost: { wood: 50, plank: 8, stone: 25 }, ratio: 1.16,
      require: { tech: "agriculture" },
      storage: { food: 180, fiber: 40 },
    },
    warehouse: {
      name: "仓储", tab: "river", era: "聚落",
      desc: "分类、堆叠、记账。文明从不再把物品丢弃在地面开始。",
      cost: { wood: 60, stone: 40, plank: 12 }, ratio: 1.17,
      require: { tech: "construction" },
      storage: { water: 80, wood: 80, stone: 80, ore: 40, metal: 20, fiber: 40, plank: 50, brick: 50, meat: 30, hide: 30, cloth: 30, meal: 40 },
    },
    cellar: {
      name: "地窖", tab: "river", era: "聚落",
      desc: "把熟食、兽肉与块茎送进凉爽的地下。霜降季因此可以谈判。",
      cost: { wood: 40, stone: 30, fiber: 16 }, ratio: 1.16,
      require: { tech: "cookery" },
      storage: { food: 120, meal: 80, meat: 60 },
    },
    stockyard: {
      name: "堆料场", tab: "river", era: "聚落",
      desc: "石料、矿石、金属与原木分堆。地面不再是仓库。",
      cost: { wood: 50, stone: 30, plank: 10 }, ratio: 1.16,
      require: { tech: "tools" },
      storage: { stone: 90, ore: 70, metal: 40, wood: 50 },
    },
    remnantShelf: {
      name: "残卷架", tab: "river", era: "智库",
      desc: "把可以触摸的记忆立起来。纸页怕潮，架子不怕。",
      cost: { plank: 18, wood: 22, fiber: 14 }, ratio: 1.15,
      require: { tech: "writing" },
      storage: { remnant: 45 },
    },
    chartCase: {
      name: "星图柜", tab: "river", era: "智库",
      desc: "星图必须平放。折叠会让坐标说谎。",
      cost: { plank: 24, metal: 10, remnant: 1 }, ratio: 1.16,
      require: { tech: "mathematics" },
      storage: { starchart: 24 },
    },
    batteryBank: {
      name: "蓄电池组", tab: "river", era: "工业",
      desc: "把白天的电流关进夜里。",
      cost: { metal: 28, brick: 16, energy: 24 }, ratio: 1.16,
      require: { tech: "electricity" },
      storage: { energy: 200 },
    },
    alloyRack: {
      name: "合金货架", tab: "river", era: "工业",
      desc: "合金比铁料更值得垫高。锈迹会毁掉归乡的龙骨。",
      cost: { brick: 22, metal: 18, alloy: 4 }, ratio: 1.16,
      require: { tech: "steel" },
      storage: { alloy: 55, metal: 15 },
    },
    fuelTank: {
      name: "燃料罐", tab: "river", era: "工业",
      desc: "密封、接地、远离火塘。燃料记得自己想变成火焰。",
      cost: { metal: 24, brick: 20, stone: 18 }, ratio: 1.16,
      require: { tech: "chemistry" },
      storage: { fuel: 80 },
    },
    circuitCase: {
      name: "元件柜", tab: "river", era: "先进",
      desc: "电路怕灰尘。柜子比桌面更像实验室。",
      cost: { metal: 18, alloy: 8, plank: 14 }, ratio: 1.16,
      require: { tech: "electronics" },
      storage: { circuit: 30 },
    },
    hazardVault: {
      name: "约束窖", tab: "river", era: "先进",
      desc: "反物质与时空结晶不能和木板住在同一间屋子里。",
      cost: { alloy: 22, circuit: 10, brick: 36, energy: 50 }, ratio: 1.18,
      require: { tech: "nuclear" },
      storage: { antimatter: 8, crystal: 6 },
    },
    lumberShed: {
      name: "木料棚", tab: "river", era: "聚落",
      desc: "把木板架离地面，盖顶遮住河雾。平面怕潮。",
      cost: { wood: 42, plank: 8, fiber: 18, stone: 12 }, ratio: 1.16,
      require: { tech: "construction" },
      storage: { plank: 90, wood: 40 },
    },
    waterTank: {
      name: "蓄水池", tab: "river", era: "聚落",
      desc: "用石料与黏土封住水面。清水不再只靠敞开的土坑。",
      cost: { stone: 48, fiber: 22, wood: 18, water: 40 }, ratio: 1.15,
      require: { tech: "irrigation" },
      storage: { water: 220 },
    },
    archive: {
      name: "残档接口", tab: "river", era: "智库",
      desc: "用藤条和卵石给芯片接出第一根「外设」。知识开始外溢。",
      cost: { wood: 28, stone: 12, fiber: 16 }, ratio: 1.15,
      require: { tech: "fire" },
      production: { knowledge: 0.18 }, storage: { knowledge: 220 },
    },
    mine: {
      name: "矿坑", tab: "river", era: "工业",
      desc: "山体里有铁矿。铁矿里有地球。",
      cost: { wood: 70, stone: 55, plank: 10 }, ratio: 1.16,
      require: { tech: "mining" },
      production: { ore: 0.2 }, storage: { ore: 60 },
    },
    oreBin: {
      name: "矿石堆场", tab: "river", era: "工业",
      desc: "矿石按块码放。潮湿的矿会结块，也会骗人。",
      cost: { wood: 36, stone: 28, plank: 8 }, ratio: 1.16,
      require: { tech: "mining" },
      storage: { ore: 100, stone: 20 },
    },
    deepShaft: {
      name: "竖井", tab: "river", era: "工业",
      desc: "向下比向岸边走得更远。原木用来撑住不想塌下来的岩层。",
      cost: { wood: 80, stone: 50, plank: 16 }, ratio: 1.16,
      require: { tech: "mining" },
      production: { ore: 0.28, stone: 0.06 }, consumption: { wood: 0.05 }, storage: { ore: 40 },
    },
    furnace: {
      name: "冶炼炉", tab: "river", era: "工业",
      desc: "河风灌入炉口。金属第一次在这颗星球上按人类的意志流动。",
      cost: { stone: 80, wood: 40, ore: 20 }, ratio: 1.16,
      require: { tech: "smelting" },
      production: { metal: 0.07 }, consumption: { ore: 0.11, wood: 0.04 }, storage: { metal: 25 },
    },
    kiln: {
      name: "砖窑", tab: "river", era: "工业",
      desc: "石料、清水、火焰。砖石从此可以按人的尺寸生长。",
      cost: { stone: 50, wood: 28, fiber: 12 }, ratio: 1.16,
      require: { tech: "smelting" },
      production: { brick: 0.055 }, consumption: { stone: 0.18, water: 0.04, wood: 0.05 }, storage: { brick: 40 },
    },
    bloomery: {
      name: "锻炉", tab: "river", era: "工业",
      desc: "比冶炼炉更早、更吵。铁料在锤声里学会自己的形状。",
      cost: { stone: 55, wood: 30, ore: 12 }, ratio: 1.16,
      require: { tech: "smelting" },
      production: { metal: 0.09 }, consumption: { ore: 0.14, wood: 0.08 }, storage: { metal: 20 },
    },
    brickYard: {
      name: "砖垛场", tab: "river", era: "工业",
      desc: "砖石怕水。垫高、错缝、盖顶，像岸上的一座矮丘。",
      cost: { stone: 40, brick: 10, wood: 24, fiber: 12 }, ratio: 1.16,
      require: { tech: "smelting" },
      storage: { brick: 90, stone: 40 },
    },
    ingotShed: {
      name: "锭料棚", tab: "river", era: "工业",
      desc: "金属怕水。垫高、盖顶、错缝码放。",
      cost: { brick: 16, wood: 28, metal: 6 }, ratio: 1.16,
      require: { tech: "smelting" },
      storage: { metal: 70, ore: 20 },
    },
    mill: {
      name: "水车", tab: "river", era: "工业",
      desc: "河水开始推动水车。",
      cost: { wood: 90, plank: 20, stone: 40, rope: 0 }, ratio: 1.15,
      require: { tech: "mechanics" },
      production: { energy: 0.35 }, storage: { energy: 50 },
    },
    pump: {
      name: "水泵", tab: "river", era: "工业",
      desc: "齿轮把河水抬起来。能源换成清水。",
      cost: { metal: 18, plank: 16, stone: 24 }, ratio: 1.15,
      require: { tech: "mechanics" },
      production: { water: 0.4 }, consumption: { energy: 0.08 },
    },
    academy: {
      name: "学堂", tab: "river", era: "智库",
      desc: "教居民辨认地球文字。他们把「三体」念成一种鸟鸣。",
      cost: { plank: 28, stone: 60, knowledge: 80, brick: 10 }, ratio: 1.16,
      require: { tech: "writing" },
      production: { knowledge: 0.32 }, storage: { knowledge: 400 },
      flags: { scholarBonus: 0.08 },
    },
    longhouse: {
      name: "长屋", tab: "river", era: "聚落",
      desc: "火塘连成一条。夜晚能听见居民学着你的语言做梦。",
      cost: { wood: 80, plank: 25, brick: 20, fiber: 30 }, ratio: 1.17,
      require: { tech: "writing" },
      housing: 5,
      flags: { happiness: 3 },
    },
    guestHall: {
      name: "专属客馆", tab: "river", era: "聚落",
      desc: "两间相连的客房。高级居民在这里过夜，才会留下。",
      cost: { wood: 110, plank: 38, brick: 24, stone: 52, fiber: 28 }, ratio: 1.18,
      require: { tech: "writing" },
      housingElite: 2,
      flags: { happiness: 2 },
    },
    observatory: {
      name: "观测台", tab: "river", era: "智库",
      desc: "你终于看见太阳系。地球是一粒将要熄灭的尘埃。",
      cost: { plank: 40, metal: 20, knowledge: 200, brick: 30 }, ratio: 1.16,
      require: { tech: "mathematics" },
      production: { knowledge: 0.22, starchart: 0.004 }, storage: { knowledge: 600, starchart: 8 },
      flags: { concealment: -0.4 },
    },
    dam: {
      name: "河坝电站", tab: "river", era: "工业",
      desc: "把一条河流按住。能量从此不再依靠运气。",
      cost: { brick: 40, metal: 35, plank: 30, stone: 100 }, ratio: 1.17,
      require: { tech: "electricity" },
      production: { energy: 1.15 }, storage: { energy: 120 },
    },
    lab: {
      name: "实验室", tab: "river", era: "智库",
      desc: "无菌是一种奢侈。你用沸水与金属逼近无菌。",
      cost: { metal: 40, brick: 35, knowledge: 400, energy: 40 }, ratio: 1.16,
      require: { tech: "electricity" },
      production: { knowledge: 0.55 }, storage: { knowledge: 900 },
    },
    foundry: {
      name: "合金厂", tab: "river", era: "工业",
      desc: "比铁料更硬的材料。归乡的龙骨需要这种材料。",
      cost: { metal: 50, brick: 40, energy: 30, stone: 60 }, ratio: 1.17,
      require: { tech: "steel" },
      production: { alloy: 0.05 }, consumption: { metal: 0.08, energy: 0.12 }, storage: { alloy: 20 },
    },
    solar: {
      name: "光伏阵", tab: "river", era: "工业",
      desc: "这颗恒星比太阳略偏橙色。芯片里的曲线仍然能用。",
      cost: { alloy: 15, circuit: 6, metal: 30 }, ratio: 1.16,
      require: { tech: "electronics" },
      production: { energy: 0.85 }, storage: { energy: 80 },
    },
    factory: {
      name: "装配厂", tab: "river", era: "工业",
      desc: "流水线。居民第一次看见「重复」变成力量。",
      cost: { alloy: 20, brick: 50, metal: 40, circuit: 4 }, ratio: 1.18,
      require: { tech: "electronics" },
      production: { circuit: 0.012 }, consumption: { alloy: 0.02, energy: 0.2 },
      flags: { craftBonus: 0.1 },
    },
    clonevat: {
      name: "培育舱", tab: "river", era: "先进",
      desc: "义体技术的远亲。用培育来续写生命。",
      cost: { alloy: 25, circuit: 12, knowledge: 800, energy: 80 }, ratio: 1.18,
      require: { tech: "computing" },
      housing: 8,
    },
    guestCourt: {
      name: "专属院落", tab: "river", era: "先进",
      desc: "围墙、灯火与单独的水源。神话级居民也肯在此落脚。",
      cost: { brick: 48, plank: 42, metal: 30, alloy: 14, fiber: 36 }, ratio: 1.2,
      require: { tech: "electricity" },
      housingElite: 3,
      flags: { happiness: 4 },
    },
    reactor: {
      name: "裂变堆", tab: "river", era: "先进",
      desc: "把一颗小太阳关进河岸的水泥里。导师会责骂你，也会点头。",
      cost: { alloy: 40, circuit: 18, metal: 80, remnant: 10 }, ratio: 1.2,
      require: { tech: "nuclear" },
      production: { energy: 3.2, antimatter: 0.001 }, consumption: { ore: 0.15 }, storage: { energy: 200, antimatter: 3 },
      flags: { concealment: -1.2 },
    },
    pad: {
      name: "发射坪", tab: "space", era: "星空",
      desc: "第一枚箭矢指向地球曾经的方向。烟柱会说话。",
      cost: { alloy: 30, fuel: 20, circuit: 8, brick: 40 }, ratio: 1.18,
      require: { tech: "rocketry" },
      production: { fleet: 0.06, starchart: 0.01 }, consumption: { fuel: 0.05, energy: 0.3 },
      flags: { concealment: -2.2 },
    },
    dock: {
      name: "轨道船坞", tab: "space", era: "星空",
      desc: "在没有月亮的夜空里，多出一座人造的月亮。",
      cost: { alloy: 50, circuit: 20, fuel: 30, starchart: 8 }, ratio: 1.2,
      require: { tech: "orbital" },
      production: { fleet: 0.22 }, consumption: { energy: 0.8, alloy: 0.03 },
      flags: { concealment: -1.5 },
    },
    jammer: {
      name: "智子干扰塔", tab: "space", era: "星空",
      desc: "导师留下的禁术：让智子在这里「近视」。",
      cost: { alloy: 35, circuit: 25, remnant: 15, knowledge: 2000 }, ratio: 1.22,
      require: { tech: "sophon" },
      flags: { concealment: 6, concealRegen: 0.35 },
    },
    anchorArray: {
      name: "锚点阵列", tab: "anchor", era: "时间",
      desc: "把河边那一秒钟放大。充能时，空气会像要裂开。",
      cost: { alloy: 20, circuit: 10, crystal: 1, energy: 100 }, ratio: 1.2,
      require: { tech: "timeanchor" },
      production: { charge: 0.035, crystal: 0.0008 }, consumption: { energy: 0.4 },
    },
    drive: {
      name: "曲率环", tab: "space", era: "归乡",
      desc: "回家的门户。门后是2300年的地球，以及已经到达的舰队。",
      cost: { alloy: 80, circuit: 40, antimatter: 4, crystal: 3, fleet: 0 }, ratio: 1.25,
      require: { tech: "curvature" },
      production: { fleet: 1.1 }, consumption: { antimatter: 0.002, energy: 2 },
      flags: { concealment: -3 },
    },
  },

  jobs: {
    forager: {
      name: "采集者",
      desc: "在河滩与林缘之间走一条不会迷路的道路。",
      production: { food: 0.16, fiber: 0.05 },
      require: {},
    },
    cutter: {
      name: "伐木工",
      desc: "只砍已标记的树木。居民比你更怕林子里的生物。",
      production: { wood: 0.14 },
      require: { tech: "construction" },
    },
    sawyer: {
      name: "锯木工",
      desc: "把倒木变成可以叠放的形状。",
      production: { wood: 0.08, plank: 0.015 },
      require: { tech: "forestry" },
    },
    mason: {
      name: "石工",
      desc: "锤声成为聚落的第二种心跳。",
      production: { stone: 0.11 },
      require: { tech: "tools" },
    },
    miner: {
      name: "矿工",
      desc: "地下没有智子。他们喜欢这一点。",
      production: { ore: 0.09, stone: 0.03 },
      require: { tech: "mining" },
    },
    decoder: {
      name: "解码者",
      desc: "对着空气朗读芯片里的句子，直到句子变成工具。",
      production: { knowledge: 0.13 },
      require: { tech: "writing" },
    },
    operator: {
      name: "司炉",
      desc: "盯着火焰，也盯着温度。金属讨厌走神的人。",
      production: { metal: 0.035, energy: 0.06 },
      require: { tech: "smelting" },
    },
    herder: {
      name: "牧人",
      desc: "跟着牲畜走，也让牲畜跟着栅栏走。",
      production: { meat: 0.08, hide: 0.03 },
      require: { tech: "husbandry" },
    },
    cook: {
      name: "厨子",
      desc: "把生的变成可以分享的。火塘因此有了纪律。",
      production: { meal: 0.05 },
      require: { tech: "cookery" },
    },
    weaver: {
      name: "织工",
      desc: "经线不会自己交叉。双手必须记得每一次穿过。",
      production: { cloth: 0.03 },
      require: { tech: "weaving" },
    },
    technician: {
      name: "技术员",
      desc: "把地球的电路图翻译成这颗星球能懂的语言。",
      production: { circuit: 0.006, energy: 0.04 },
      require: { tech: "electronics" },
    },
    keeper: {
      name: "守锚人",
      desc: "坐在河边，确认这一刻仍可被返回。",
      production: { charge: 0.01 },
      flags: { happiness: 0.8 },
      require: { tech: "timeanchor" },
    },
  },

  techs: {
    fire: {
      name: "用火", era: "生存", order: 1,
      desc: "湿木、火花、以及义体里残存的点火程序。夜晚被推开一寸。",
      cost: { wood: 15, fiber: 8, food: 8 },
      unlocks: "火塘、残档接口、烹饪。知识开始可被唤起。",
    },
    cookery: {
      name: "烹饪", era: "生存", order: 1.5,
      desc: "火焰不只用来驱赶黑暗。它开始改变食物的名字。",
      cost: { knowledge: 28, wood: 18, food: 12 },
      require: { tech: "fire" },
      unlocks: "灶台、熏棚、地窖、厨子、熟食。",
    },
    survival: {
      name: "生存学", era: "生存", order: 2,
      desc: "芯片打开《野外生存》的第一页。纸张不存在，文字直接烙在视野上。",
      cost: { knowledge: 20, food: 20 },
      require: { tech: "fire" },
      unlocks: "采集效率提升。",
      flags: { gatherBonus: 0.25 },
    },
    construction: {
      name: "构架", era: "生存", order: 3,
      desc: "横梁、立柱、斜撑。棚屋不再只是「靠在一起的木头」。",
      cost: { knowledge: 35, wood: 30, fiber: 20 },
      require: { tech: "fire" },
      unlocks: "棚屋、林场、仓储、专属厢房、招募抽签、探索、育林。",
    },
    forestry: {
      name: "育林", era: "聚落", order: 3.5,
      desc: "倒木会用尽。先让树木按你的节奏生长。",
      cost: { knowledge: 55, wood: 40, fiber: 16 },
      require: { tech: "construction" },
      unlocks: "锯木棚、炭窑、苗圃、锯木工。",
    },
    tools: {
      name: "工具", era: "生存", order: 4,
      desc: "刃口改变物种的命运。你把这句话讲给居民听，他们把石头磨得更好。",
      cost: { knowledge: 50, wood: 25, stone: 20 },
      require: { tech: "construction" },
      unlocks: "采石场、石工、板车、纺织、堆料场。",
    },
    weaving: {
      name: "纺织", era: "聚落", order: 4.5,
      desc: "纤维交叉之后，寒冷开始退让。",
      cost: { knowledge: 80, fiber: 30, wood: 20 },
      require: { tech: "tools" },
      unlocks: "织机、布仓、缝衣间、织工、布匹。",
    },
    agriculture: {
      name: "农耕", era: "聚落", order: 5,
      desc: "不要跟随浆果，要让浆果跟随你。",
      cost: { knowledge: 70, food: 40, water: 40, fiber: 25 },
      require: { tech: "survival" },
      unlocks: "河滩田、粮仓、果园、畜牧。",
    },
    husbandry: {
      name: "畜牧", era: "聚落", order: 5.5,
      desc: "不要只跟随猎物。让猎物在栅栏里繁殖。",
      cost: { knowledge: 90, food: 35, water: 30 },
      require: { tech: "agriculture" },
      unlocks: "畜栏、牧地、鞣皮棚、牧人、兽肉、皮革。",
    },
    mining: {
      name: "采矿", era: "聚落", order: 6,
      desc: "地球的工业革命在一处河岸被重新点燃。",
      cost: { knowledge: 120, stone: 40, wood: 40 },
      require: { tech: "tools" },
      unlocks: "矿坑、矿工、矿石堆场、竖井。",
    },
    smelting: {
      name: "冶炼", era: "工业", order: 7,
      desc: "矿石承认自己内部藏着另一种形状。",
      cost: { knowledge: 180, ore: 25, stone: 50, wood: 30 },
      require: { tech: "mining" },
      unlocks: "冶炼炉、司炉、金属、砖窑、锻炉、锭料棚。",
    },
    writing: {
      name: "残档编目", era: "智库", order: 8,
      desc: "知识若不被编目，就只是胸腔里的噪音。",
      cost: { knowledge: 160, wood: 40, fiber: 30 },
      require: { tech: "survival" },
      unlocks: "学堂、长屋、解码者、工坊残卷、专属客馆、残卷架。",
    },
    mathematics: {
      name: "数学", era: "智库", order: 9,
      desc: "导师曾说：三体人能锁死物理，却锁不死你在河边用树枝画的圆形。",
      cost: { knowledge: 280, remnant: 1 },
      require: { tech: "writing" },
      unlocks: "观测台、星图柜。",
    },
    mechanics: {
      name: "机械", era: "工业", order: 10,
      desc: "齿轮比肌肉诚实。",
      cost: { knowledge: 320, metal: 15, plank: 20, wood: 50 },
      require: { tech: "smelting" },
      unlocks: "水车、河舟、水泵。",
    },
    irrigation: {
      name: "水利", era: "聚落", order: 11,
      desc: "你开始管理一条河流，而不仅仅是向它乞讨清水。",
      cost: { knowledge: 240, water: 80, stone: 60 },
      require: { tech: "agriculture" },
      unlocks: "清水产出提升、水井、蓄水池。",
      flags: { waterProd: 0.2 },
    },
    electricity: {
      name: "电力", era: "工业", order: 12,
      desc: "黑暗被重新定义。义体第一次感到「故乡的电流」。",
      cost: { knowledge: 520, metal: 30, energy: 40 },
      require: { tech: "mechanics" },
      unlocks: "河坝电站、实验室、专属院落、蒸汽车、蓄电池组。",
    },
    chemistry: {
      name: "化学", era: "工业", order: 13,
      desc: "把物质拆开再组装。燃料有了名字。",
      cost: { knowledge: 700, ore: 40, food: 60, energy: 30 },
      require: { tech: "electricity" },
      unlocks: "燃料精炼、燃料罐。",
    },
    steel: {
      name: "合金工艺", era: "工业", order: 14,
      desc: "铁料的孩子。比父辈更适合离开地面。",
      cost: { knowledge: 900, metal: 50, energy: 50 },
      require: { tech: "chemistry" },
      unlocks: "合金厂、合金货架。",
    },
    electronics: {
      name: "电子", era: "先进", order: 15,
      desc: "芯片终于遇见了它在这颗星球上的亲戚。",
      cost: { knowledge: 1400, metal: 40, remnant: 4, energy: 80 },
      require: { tech: "electricity" },
      unlocks: "光伏、装配厂、技术员、电路、浮橇、元件柜。",
    },
    computing: {
      name: "计算重构", era: "先进", order: 16,
      desc: "你把人类的计算机科学从沙盘里重新砌起来。速度很慢。",
      cost: { knowledge: 2200, circuit: 8, remnant: 6 },
      require: { tech: "electronics" },
      unlocks: "培育舱。",
    },
    rocketry: {
      name: "推进", era: "星空", order: 17,
      desc: "第一枚火箭证明方向存在。",
      cost: { knowledge: 3000, fuel: 20, alloy: 15, starchart: 3 },
      require: { tech: "steel" },
      unlocks: "发射坪、星空页签。",
    },
    orbital: {
      name: "轨道", era: "星空", order: 18,
      desc: "离开地面之后，河声消失。你这才意识到自己有多想念河声。",
      cost: { knowledge: 4500, starchart: 8, alloy: 25, circuit: 12 },
      require: { tech: "rocketry" },
      unlocks: "轨道船坞。",
    },
    nuclear: {
      name: "核能", era: "先进", order: 19,
      desc: "面壁者曾用过更疯狂的手段。你只要一座安分的反应堆。",
      cost: { knowledge: 6000, alloy: 30, remnant: 10, energy: 200 },
      require: { tech: "computing" },
      unlocks: "裂变堆、微量反物质、约束窖。",
    },
    sophon: {
      name: "智子理论", era: "星空", order: 20,
      desc: "二维展开的宇宙探针。这里仍是盲区——只要你不朝地球大声说话。",
      cost: { knowledge: 7500, starchart: 12, remnant: 12, circuit: 15 },
      require: { tech: "orbital" },
      unlocks: "智子干扰塔。理解隐蔽。",
    },
    relativity: {
      name: "相对论残篇", era: "时间", order: 21,
      desc: "时间不是河流。时间是你可以抛锚的海洋。",
      cost: { knowledge: 5000, remnant: 8 },
      require: { tech: "mathematics" },
      unlocks: "时空结晶的理论门槛。",
    },
    timeanchor: {
      name: "锚点原理", era: "时间", order: 22,
      desc: "导师把名字说完了：锚点，是为了回去；时间，是为了再走一次。",
      cost: { knowledge: 9000, remnant: 15, energy: 250, crystal: 1 },
      require: { tech: "relativity" },
      unlocks: "锚点阵列、守锚人、回溯。",
    },
    darkforest: {
      name: "黑暗森林", era: "星空", order: 23,
      desc: "宇宙是一座黑暗森林。你在林中点起一堆必须被看见的火焰。",
      cost: { knowledge: 10000, starchart: 16, remnant: 10 },
      require: { tech: "sophon" },
      unlocks: "舰队效率提升，隐蔽消耗降低。",
      flags: { fleetBonus: 0.2, concealRelief: 0.25 },
    },
    curvature: {
      name: "曲率航行", era: "归乡", order: 24,
      desc: "把空间折起来。地球不再是一个无法抵达的地点。",
      cost: { knowledge: 14000, antimatter: 3, crystal: 2, starchart: 20 },
      require: { tech: "timeanchor" },
      unlocks: "曲率环。",
    },
    deterrence: {
      name: "威慑", era: "归乡", order: 25,
      desc: "让对方不敢落下第二只靴子。",
      cost: { knowledge: 16000, fleet: 40, antimatter: 2, remnant: 20 },
      require: { tech: "curvature" },
      unlocks: "干预准备度大幅提升。",
      flags: { readyBonus: 25 },
    },
    homecoming: {
      name: "归乡", era: "归乡", order: 26,
      desc: "坐标锁定：太阳系。时间锁定：舰队抵达的那一日。你将带着一条河流的文明回去。",
      cost: { knowledge: 20000, fleet: 80, crystal: 4, antimatter: 5, remnant: 25 },
      require: { tech: "deterrence" },
      unlocks: "启动跃迁，尝试拯救地球。",
    },
  },

  crafts: {
    plank: {
      name: "木板",
      desc: "把树木变成平面。房屋与船只都从这一步开始。",
      require: { tech: "construction" },
      cost: { wood: 5 },
      gain: { plank: 1 },
    },
    rope: {
      name: "绳索",
      desc: "纤维的军队。",
      require: { tech: "tools" },
      cost: { fiber: 4 },
      gain: { fiber: 0 },
      extra: true,
    },
    brick: {
      name: "砖石",
      desc: "火焰与泥土的契约。",
      require: { tech: "smelting" },
      cost: { stone: 3, water: 1, wood: 1 },
      gain: { brick: 1 },
    },
    mealCraft: {
      name: "烹制熟食",
      desc: "把块茎与兽肉交给火焰。熟食比生食更能留住人。",
      require: { tech: "cookery" },
      cost: { food: 2, meat: 1, water: 1 },
      gain: { meal: 2 },
    },
    clothCraft: {
      name: "织布",
      desc: "纤维与皮革交叉成匹。",
      require: { tech: "weaving" },
      cost: { fiber: 6, hide: 1 },
      gain: { cloth: 1 },
    },
    metalCraft: {
      name: "手工炼金",
      desc: "炉火不足时，改用更原始的方法。",
      require: { tech: "smelting" },
      cost: { ore: 4, wood: 2 },
      gain: { metal: 1 },
    },
    alloy: {
      name: "锻造合金",
      desc: "反复折叠，直到它记得地球的标准。",
      require: { tech: "steel" },
      cost: { metal: 3, energy: 2 },
      gain: { alloy: 1 },
    },
    fuel: {
      name: "精炼燃料",
      desc: "从植物与矿脉里挤出离开地面的资格。",
      require: { tech: "chemistry" },
      cost: { fiber: 6, ore: 2, energy: 2 },
      gain: { fuel: 1 },
    },
    remnant: {
      name: "装订残卷",
      desc: "把芯片里的一章按在木板上。学堂需要可以触摸的记忆。",
      require: { tech: "writing" },
      cost: { knowledge: 60, plank: 2, fiber: 4 },
      gain: { remnant: 1 },
    },
    circuit: {
      name: "蚀刻电路",
      desc: "双手会发抖。发抖也要刻下去。",
      require: { tech: "electronics" },
      cost: { alloy: 2, knowledge: 40, energy: 3 },
      gain: { circuit: 1 },
    },
    starchart: {
      name: "测绘星图",
      desc: "每一张图都在问：地球还在吗？",
      require: { tech: "mathematics" },
      cost: { knowledge: 120, remnant: 1 },
      gain: { starchart: 1 },
    },
    crystal: {
      name: "凝结时空结晶",
      desc: "锚点充能溢出时，河边的沙子会变成这种结晶。",
      require: { tech: "relativity" },
      cost: { energy: 80, knowledge: 200, remnant: 2 },
      gain: { crystal: 1 },
    },
    antimatter: {
      name: "约束反物质",
      desc: "用磁场抱住一滴会吞掉世界的露水。",
      require: { tech: "nuclear" },
      cost: { energy: 150, alloy: 4, circuit: 2 },
      gain: { antimatter: 1 },
    },
  },

  upgrades: {
    sharpFlint: {
      name: "燧石刃",
      desc: "采集、剥麻、拾柴效率 +25%。",
      require: { tech: "tools" },
      cost: { stone: 30, fiber: 20, knowledge: 40 },
      flags: { gatherBonus: 0.25 },
    },
    cropRotate: {
      name: "轮作",
      desc: "食物建筑产出 +20%。",
      require: { tech: "agriculture" },
      cost: { food: 80, knowledge: 100, water: 50 },
      flags: { foodProd: 0.2 },
    },
    smokeCure: {
      name: "熏制",
      desc: "熟食产出 +20%。",
      require: { tech: "cookery" },
      cost: { food: 40, meat: 8, knowledge: 60, wood: 20 },
      flags: { mealProd: 0.2 },
    },
    spindle: {
      name: "纺轮",
      desc: "布匹产出 +25%。",
      require: { tech: "weaving" },
      cost: { fiber: 40, wood: 20, knowledge: 80 },
      flags: { clothProd: 0.25 },
    },
    pulley: {
      name: "滑轮组",
      desc: "原木与石料建筑产出 +20%。",
      require: { tech: "mechanics" },
      cost: { plank: 20, fiber: 40, knowledge: 200 },
      flags: { woodStoneProd: 0.2 },
    },
    bellows: {
      name: "鼓风",
      desc: "金属产出 +30%。",
      require: { tech: "smelting" },
      cost: { wood: 60, fiber: 30, knowledge: 180 },
      flags: { metalProd: 0.3 },
    },
    catalog: {
      name: "残档压缩",
      desc: "知识产出 +25%，知识上限 +20%。",
      require: { tech: "writing" },
      cost: { remnant: 3, knowledge: 300, plank: 15 },
      flags: { knowledgeProd: 0.25, knowledgeCap: 0.2 },
    },
    silentBus: {
      name: "静默总线",
      desc: "建筑造成的隐蔽损耗 -35%。",
      require: { tech: "electronics" },
      cost: { circuit: 6, remnant: 5, knowledge: 800 },
      flags: { concealRelief: 0.35 },
    },
    assembly: {
      name: "标准件",
      desc: "工坊每次额外获得 1 个产物（按比例）。",
      require: { tech: "electronics" },
      cost: { circuit: 8, alloy: 20, knowledge: 1000 },
      flags: { extraCraft: 0.5 },
    },
    autoCraft: {
      name: "自动装配",
      desc: "每秒自动尝试制作木板、砖石、燃料。对应仓储已满时停止。",
      require: { tech: "computing" },
      cost: { circuit: 12, alloy: 25, knowledge: 1800 },
      flags: { autoCraft: true },
    },
    deepMine: {
      name: "深井",
      desc: "矿石产出 +40%。",
      require: { tech: "mining" },
      cost: { metal: 20, wood: 80, knowledge: 400 },
      flags: { oreProd: 0.4 },
    },
    hydroTune: {
      name: "水轮机叶片",
      desc: "能源产出 +25%。",
      require: { tech: "electricity" },
      cost: { metal: 25, plank: 20, knowledge: 500 },
      flags: { energyProd: 0.25 },
    },
    darkProtocol: {
      name: "黑暗协议",
      desc: "舰队产出 +15%，隐蔽再生 +0.2/秒。",
      require: { tech: "darkforest" },
      cost: { starchart: 10, circuit: 10, remnant: 8 },
      flags: { fleetBonus: 0.15, concealRegen: 0.2 },
    },
  },

  metaphysics: {
    muscle: {
      name: "肌肉记忆",
      desc: "每次手动采集产量 +100%。回溯后仍记得双手怎么动作。",
      cost: 8,
      flags: { gatherBonus: 1 },
    },
    echo: {
      name: "河岸回响",
      desc: "新的一轮开局即拥有 1 座蓄水坑与 1 座采集丛。",
      cost: 15,
      flags: { startBuildings: { cistern: 1, grove: 1 } },
    },
    decode: {
      name: "加速解码",
      desc: "知识产出 +30%。",
      cost: 22,
      flags: { knowledgeProd: 0.3 },
    },
    cache: {
      name: "仓储直觉",
      desc: "所有资源上限 +35%。",
      cost: 28,
      flags: { allCap: 0.35 },
    },
    veil: {
      name: "隐蔽协议",
      desc: "隐蔽基础值 +20，损耗 -20%。",
      cost: 36,
      flags: { concealBase: 20, concealRelief: 0.2 },
    },
    reactor: {
      name: "余烬反应",
      desc: "全局产出 +12%。",
      cost: 48,
      flags: { globalProd: 0.12 },
    },
    mentor: {
      name: "导师残响",
      desc: "开局即掌握用火、生存学与构架。",
      cost: 64,
      flags: { startTechs: ["fire", "survival", "construction"] },
    },
    heartbeat: {
      name: "第二次心跳",
      desc: "锚点充能速度 +80%。",
      cost: 80,
      flags: { chargeBonus: 0.8 },
    },
  },

  drawBase: { food: 16, water: 16 },
  elitePower: {
    common: { hp: 14, atk: 2.2 },
    expert: { hp: 20, atk: 3.4 },
    epic: { hp: 28, atk: 4.8 },
    legendary: { hp: 40, atk: 6.8 },
    mythic: { hp: 56, atk: 9.4 },
  },
  zoneKinds: {
    plain: { id: "plain", name: "普通区块", desc: "河岸外的土地。采集常见物资，危险较低。" },
    rare: { id: "rare", name: "稀有区块", desc: "地层里藏着营地没有的材料。" },
    combat: { id: "combat", name: "战斗区块", desc: "对岸那些眼睛在这里不再只是张望。" },
    boss: { id: "boss", name: "首领区块", desc: "一块被巨大生物占据的土地。击败后才能真正踏平。" },
  },
  vehicles: {
    foot: { id: "foot", name: "步行", desc: "沿着河岸与兽径走。越远越慢。", speed: 1, cargo: 0, cost: {}, require: {} },
    raft: { id: "raft", name: "木筏", desc: "让河流替双腿做一部分工作。", speed: 1.55, cargo: 6, cost: { wood: 48, fiber: 28 }, require: { tech: "construction" } },
    wagon: { id: "wagon", name: "板车", desc: "木板、轮轴、以及不再用肩胛骨去扛石头。", speed: 2.1, cargo: 12, cost: { plank: 32, fiber: 20, stone: 16 }, require: { tech: "tools", vehicle: "raft" } },
    boat: { id: "boat", name: "河舟", desc: "桨与舵。前往时间开始缩短。", speed: 2.9, cargo: 16, cost: { plank: 48, fiber: 24, metal: 8 }, require: { tech: "mechanics", vehicle: "wagon" } },
    steam: { id: "steam", name: "蒸汽车", desc: "把锅炉绑上轮子。远处的区块变得可以当天往返。", speed: 4, cargo: 22, cost: { metal: 36, brick: 24, energy: 40 }, require: { tech: "electricity", vehicle: "boat" } },
    hover: { id: "hover", name: "浮橇", desc: "贴着地面滑动。智子看不见，兽类也很难追上。", speed: 5.6, cargo: 28, cost: { alloy: 18, circuit: 8, energy: 50 }, require: { tech: "electronics", vehicle: "steam" } },
  },
  zones: [],
  eliteNamesByRarity: {
    common: ["第谷", "哈雷", "赫歇尔", "拉瓦锡", "道尔顿", "门捷列夫", "焦耳", "安培", "欧姆", "赫兹", "狄拉克", "庞加莱", "伯努利", "胡克", "卡文迪许", "伽罗瓦", "黎曼", "柯西", "阿贝尔", "林奈", "拉马克", "华莱士", "詹纳", "南丁格尔", "西塞罗", "修昔底德", "休谟", "霍布斯", "李嘉图", "维瓦尔第", "鉴真", "郦道元", "詹天佑", "开尔文", "康托尔", "奥斯特", "基尔霍夫", "布丰", "德彪西", "勒让德"],
    expert: ["莱布尼茨", "帕斯卡", "普朗克", "费曼", "香农", "孟德尔", "哈维", "希波克拉底", "托勒密", "希罗多德", "卢梭", "黑格尔", "亚当斯密", "马基雅维利", "洛克", "莫奈", "柴可夫斯基", "玄奘", "郑和", "蔡伦", "毕昇", "鲁班", "墨子", "扁鹊", "华佗", "沈括", "徐霞客", "商鞅", "管仲", "织田信长", "萨拉丁", "傅里叶", "拉普拉斯", "伦琴", "冯诺依曼", "海森堡"],
    epic: ["法拉第", "麦克斯韦", "欧拉", "高斯", "开普勒", "哥白尼", "图灵", "巴斯德", "瓦特", "爱迪生", "玻尔", "薛定谔", "孟子", "庄子", "韩非子", "司马迁", "苏轼", "王羲之", "张衡", "祖冲之", "李时珍", "诸葛亮", "汉尼拔", "克娄巴特拉", "伊丽莎白一世", "康熙", "彼得大帝", "霍金", "歌德", "托尔斯泰", "雨果", "肖邦"],
    legendary: ["特斯拉", "居里夫人", "阿基米德", "欧几里得", "贝多芬", "莫扎特", "巴赫", "米开朗基罗", "梵高", "李白", "杜甫", "老子", "孙子", "林肯", "丘吉尔", "武则天", "贞德", "哥伦布", "马克思", "康德", "伏尔泰", "荷马", "但丁", "曹雪芹"],
    mythic: ["牛顿", "爱因斯坦", "孔子", "达芬奇", "莎士比亚", "亚里士多德", "苏格拉底", "柏拉图", "伽利略", "达尔文", "拿破仑", "亚历山大大帝", "秦始皇", "成吉思汗", "凯撒", "华盛顿"],
  },
  rarities: {
    common: { id: "common", name: "普通", jobs: 1, bonus: 0.4, eat: 1, order: 1 },
    expert: { id: "expert", name: "专家", jobs: 1, bonus: 0.9, eat: 1.15, order: 2 },
    epic: { id: "epic", name: "史诗", jobs: 2, bonus: 0.75, eat: 1.35, order: 3 },
    legendary: { id: "legendary", name: "传奇", jobs: 2, bonus: 1.35, eat: 1.7, order: 4 },
    mythic: { id: "mythic", name: "神话", jobs: 3, bonus: 1.6, eat: 2.15, order: 5, passive: true },
  },
  elitePassives: {
    harvest: { name: "丰收余韵", desc: "食物建筑产出 +10%。", flags: { foodProd: 0.1 } },
    scholar: { name: "残档共鸣", desc: "知识产出 +10%。", flags: { knowledgeProd: 0.1 } },
    forge: { name: "炉心手感", desc: "金属产出 +12%。", flags: { metalProd: 0.12 } },
    volt: { name: "河电低语", desc: "能源产出 +10%。", flags: { energyProd: 0.1 } },
    oreSense: { name: "矿脉直觉", desc: "矿石产出 +12%。", flags: { oreProd: 0.12 } },
    gather: { name: "拾荒本能", desc: "手动采集 +18%。", flags: { gatherBonus: 0.18 } },
    veil: { name: "盲区呼吸", desc: "隐蔽再生 +0.18/秒。", flags: { concealRegen: 0.18 } },
    hearth: { name: "火塘守夜", desc: "安定持续回升。", flags: { happiness: 6 } },
    anchor: { name: "锚点心跳", desc: "锚点充能速度 +18%。", flags: { chargeBonus: 0.18 } },
    fleet: { name: "归乡指向", desc: "舰队产出 +10%。", flags: { fleetBonus: 0.1 } },
    cache: { name: "仓储本能", desc: "全部资源上限 +8%。", flags: { allCap: 0.08 } },
    water: { name: "清水平衡", desc: "清水产出 +12%。", flags: { waterProd: 0.12 } },
  },

  intro: [
    "白光褪去之后，先听见的是河流。\n\n不是地球的河流。水声更沉，像有什么巨大的生物在上游缓慢翻身。\n你躺在湿冷的卵石上，义体关节还在报错，胸腔里那枚芯片却已经醒了。",
    "导师的声音从骨头里渗出来，沙哑，像是录了不止一次。\n\n「如果你能听见……说明传送成功。」\n「三体舰队已经到了土星轨道。地球没有胜算。」\n「投降协议会在2300年写完最后一行。」",
    "「时间之锚不是诗。它是一个坐标。」\n「这个河边，这个时刻——只要装置充能完毕，你永远可以回来。」\n「芯片里装着人类全部的知识。但知识不能当作面包食用。」\n「你得重新把文明从泥土里抠出来。」",
    "「这里没有智子。他们看不见。这是我们最后的盲区。」\n「去探索。去创造。去发展。」\n「然后在2300年真正落下之前——把地球抢回来。」\n\n河风从对岸的黑树林里穿过来。\n有低矮的生物在灌木后张望，眼睛像两粒未打磨的石头。\n你坐起来。河水冰凉，星空陌生。\n胸腔里，时间之锚轻轻跳了一下。",
  ],

  stories: [
    { id: "wake", trigger: {}, text: "你还记得自己的名字。义体的序列号在视野角落闪烁。河水的味道像含铁的雨水。" },
    { id: "firstFire", trigger: { tech: "fire" }, text: "火焰升起来的时候，对岸有什么生物发出一声短促的鸣叫，随后退进树影。导师没在录音里提过它们。" },
    { id: "firstKitchen", trigger: { building: "kitchen", count: 1 }, text: "第一锅熟食端出来时，居民围过来。他们不再只把食物放在门口，开始在火塘边坐下等待。" },
    { id: "firstHut", trigger: { building: "hut", count: 1 }, text: "棚屋立住的第一个夜晚，三名居民走来。他们把食物放在门口，又把一块打磨过的石头放在你掌心。这是一份租约。" },
    { id: "firstPen", trigger: { building: "pen", count: 1 }, text: "畜栏合拢的时候，对岸的鸣叫停了一夜。栅栏里的生物低头吃草，像是早就在等这道围栏。" },
    { id: "archive", trigger: { building: "archive", count: 1 }, text: "残档接口接通的瞬间，两千年的农书、几何与一首没唱完的歌曲同时涌进来。你呕吐了。然后开始分类。" },
    { id: "folk", trigger: { pop: 5 }, text: "居民开始模仿你的作息。他们仍不会制造轮子，但已经会把工具放回原处。" },
    { id: "metal", trigger: { tech: "smelting" }, text: "第一块金属凝固时，你看见了自己的面孔。义体的外壳在这颗星球上第一次有了镜子。" },
    { id: "stars", trigger: { building: "observatory", count: 1 }, text: "地球的光谱还在。它还没被改写成三体的恒星。你把这件事写进日志，双手有些发抖。" },
    { id: "radio", trigger: { tech: "electronics" }, text: "你造出了无线电，又立刻把它关掉。盲区的第一条法则：不要朝黑暗森林挥手。" },
    { id: "sophon", trigger: { tech: "sophon" }, text: "智子理论被重新推演完毕。结论与导师相同：这颗星球仍是影子。但发射、跃迁、广播——都会在宇宙里划火柴。" },
    { id: "anchor", trigger: { tech: "timeanchor" }, text: "你终于听懂时间之锚的名字。回去是把一条已经走通的道路，走得更狠。" },
    { id: "fleet", trigger: { tech: "rocketry" }, text: "火箭离地。河面被光芒切成两半。居民捂住耳朵，却全部仰头。他们不知道地球，但知道你要去很远的地方。" },
    { id: "home", trigger: { tech: "homecoming" }, text: "归乡坐标写入曲率环。2300年的地球在另一头等你——投降仪式、舰队、以及仍未熄灭的人类。" },
  ],

  events: [
    { id: "flood", minDay: 8, weight: 3, text: "夜洪把上游的浮木与湿润的块茎冲到营地。", gain: { wood: 18, food: 12, water: 25 } },
    { id: "gift", minDay: 15, weight: 2, text: "居民留下一堆纤维和打磨石。他们仍不进屋，只在火光外蹲着看。", gain: { fiber: 16, stone: 10 }, requirePop: 1 },
    { id: "strayHerd", minDay: 28, weight: 2, text: "一群走失的牲畜停在畜栏外。它们把兽肉与皮革的节奏提前送到营地。", gain: { meat: 10, hide: 6, food: 8 }, require: { tech: "husbandry" } },
    { id: "chip", minDay: 20, weight: 2, text: "芯片自行解压出一页被损坏的笔记：导师的字迹，写着「先活下来」。", gain: { knowledge: 25 } },
    { id: "oreVein", minDay: 40, weight: 2, text: "霜降后山体裂开一条缝隙。矿脉像伤口一样发亮。", gain: { ore: 14, stone: 12 }, require: { tech: "mining" } },
    { id: "drought", minDay: 30, weight: 2, text: "连续无雨。蓄水坑的水位露出泥线。", lose: { water: 20 }, warn: true },
    { id: "festival", minDay: 50, weight: 1, text: "丰叶季的夜晚，居民围着火塘发出一种整齐的喉音。安定回升。", happiness: 8, requirePop: 4 },
    { id: "flicker", minDay: 120, weight: 1, text: "观测台捕捉到一次极短的智子式扰动，随即消失。像有人在宇宙外侧看了你们一眼。", concealment: -8, require: { tech: "mathematics" }, warn: true },
    { id: "emberDream", minDay: 10, weight: 1, text: "你梦见自己再次躺在河边。醒来时掌心有一粒不存在的沙子。锚点在听。", gain: { charge: 4 } },
    { id: "comet", minDay: 80, weight: 1, text: "一颗没有编目的彗星划过。星图自动补了一笔。", gain: { starchart: 2, knowledge: 40 }, require: { tech: "mathematics" } },
  ],
};

// mill cost had a dummy rope:0 — crafts.rope currently grants nothing useful.
// Fix mill to not require rope; keep rope craft as a fiber sink that grants a hidden bonus item.
TA.DATA.buildings.mill.cost = { wood: 90, plank: 20, stone: 40 };
TA.DATA.crafts.rope = {
  name: "绳索",
  desc: "纤维的军队。用于加固建筑（全局上限 +1%/次，最多 +20%）。",
  require: { tech: "tools" },
  cost: { fiber: 5 },
  gain: {},
  flags: { ropeCap: 0.01 },
};
TA.DATA.buildings.drive.cost = { alloy: 80, circuit: 40, antimatter: 4, crystal: 3 };

(function assignCamp() {
  const camp = {
    lumber: "forest", lumberShed: "forest", sawmill: "forest", charcoalPit: "forest", nursery: "forest",
    quarry: "mine", mine: "mine", oreBin: "mine", deepShaft: "mine",
    furnace: "smelt", brickYard: "smelt", kiln: "smelt", bloomery: "smelt", foundry: "smelt", ingotShed: "smelt",
    grove: "farm", paddy: "farm", cistern: "farm", orchard: "farm", well: "farm",
    pen: "stock", pasture: "stock", tannery: "stock",
    campfire: "cook", kitchen: "cook", smokehouse: "cook",
    fiberShed: "weave", loom: "weave", clothShed: "weave", tailor: "weave",
    warehouse: "store", silo: "store", waterTank: "store", cellar: "store", stockyard: "store",
    remnantShelf: "store", chartCase: "store", batteryBank: "store", alloyRack: "store",
    fuelTank: "store", circuitCase: "store", hazardVault: "store",
    mill: "industry", dam: "industry", solar: "industry", factory: "industry", reactor: "industry",
    archive: "industry", academy: "industry", lab: "industry", observatory: "industry", pump: "industry",
  };
  for (const [id, c] of Object.entries(camp)) {
    if (TA.DATA.buildings[id]) TA.DATA.buildings[id].camp = c;
  }
})();

TA.DATA.zones = (function makeZones() {
  const rings = ["河缘", "苔坡", "雾林", "页岩", "霜原", "铜谷", "夜泽", "崖径", "盲湾", "余烬"];
  const cols = ["东岸", "西滩", "北岗", "南浦", "中洲", "裂谷", "浅湾", "深林", "乱石", "静野"];
  const bosses = [19, 39, 59, 79, 99];
  const bossNames = ["河瞳兽", "页岩巨蜥", "雾中守门", "余烬巨影", "盲区残骸"];
  const combatNames = ["棘兽", "石甲虫", "雾犬", "铜鳞", "夜瞳", "岸影"];
  const list = [];
  for (let i = 0; i < 100; i++) {
    const dist = Math.floor(i / 10) + 1;
    const col = i % 10;
    const seed = ((i * 9301 + 49297) % 233280) / 233280;
    let kind = "plain";
    if (bosses.includes(i)) kind = "boss";
    else if (seed < 0.05 + dist * 0.03) kind = "combat";
    else if (seed > 0.74 - dist * 0.018) kind = "rare";
    const loot = {};
    if (kind === "plain") {
      loot.food = 3; loot.wood = 3; loot.fiber = 2; loot.stone = 2; loot.water = 2;
      if (dist >= 4) loot.ore = 1;
    } else if (kind === "rare") {
      loot.ore = 2; loot.knowledge = 2; loot.remnant = dist >= 4 ? 2 : 1;
      if (dist >= 5) loot.metal = 1;
      if (dist >= 6) loot.circuit = 1;
      if (dist >= 7) loot.starchart = 1;
      if (dist >= 8) loot.crystal = 1;
      if (dist >= 9) loot.antimatter = 1;
    } else {
      loot.food = 1; loot.stone = 2; loot.ore = 2; loot.remnant = 1; loot.meat = 2; loot.hide = 1;
      if (dist >= 6) loot.alloy = 1;
      if (kind === "boss") {
        loot.knowledge = 3;
        loot.crystal = dist >= 6 ? 2 : 1;
        loot.remnant = 3;
      }
    }
    const bidx = bosses.indexOf(i);
    const enemy = (kind === "combat" || kind === "boss") ? {
      name: kind === "boss" ? bossNames[bidx] : combatNames[i % combatNames.length],
      hp: Math.round((kind === "boss" ? 70 : 26) * dist),
      atk: (kind === "boss" ? 2.4 : 1.15) * dist,
    } : null;
    list.push({ id: i, name: rings[dist - 1] + "·" + cols[col], dist, col, kind, loot, enemy });
  }
  return list;
})();

